[project]
name = "pyaixm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "inflection>=0.5.1",
    "xsdata[cli,lxml,soap]>=25.4",
]

[dependency-groups]
dev = [
    "pytest>=8.4.0",
]
